name: Build binary package

on:
  workflow_dispatch:
    inputs:
      release_body:
        description: 'Release 描述（可选）'
        required: false
        default: ''
  # push:
  #   tags:
  #     - '*'

jobs:
  build:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          # - os: ubuntu-latest
          #   target: aarch64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
#          - os: windows-latest
#            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      # - name: Install dependencies for aarch64-unknown-linux-gnu
      #   if: matrix.target == 'aarch64-unknown-linux-gnu'
      #   run: |
      #     sudo dpkg --add-architecture arm64
      #     sudo apt-get update
      #     sudo apt-get install -y gcc-aarch64-linux-gnu pkg-config qemu-user-static libssl-dev:arm64
      #     echo "OPENSSL_DIR=/usr/aarch64-linux-gnu" >> $GITHUB_ENV
      #     echo "OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu" >> $GITHUB_ENV
      #     echo "OPENSSL_INCLUDE_DIR=/usr/include/openssl" >> $GITHUB_ENV
      #     echo "PKG_CONFIG_ALLOW_CROSS=1" >> $GITHUB_ENV
      #     echo "PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig" >> $GITHUB_ENV

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package
        run: |
          mkdir dist
          cp target/${{ matrix.target }}/release/quarkdrive-webdav* dist/ || cp target/${{ matrix.target }}/release/quarkdrive-webdav.exe dist/
          cd dist
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            7z a ../quarkdrive-webdav-${{ matrix.target }}.zip *
          else
            tar czf ../quarkdrive-webdav-${{ matrix.target }}.tar.gz *
          fi

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            quarkdrive-webdav-${{ matrix.target }}.*
          body: ${{ github.event.inputs.release_body }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 设置 Release 名称
        id: release_vars
        run: |
          echo "name=${{ github.ref_name }}" >> $GITHUB_OUTPUT

      # 你可以在后续创建 Release 的步骤中使用 ${{ steps.release_vars.outputs.name }} 作为 release 名称
      # ${{ github.event.inputs.release_body }} 可作为 release 描述
